from collections import defaultdict

categories = {
    "Fruits": [
        ("Citrus Fruits", ["navel orange", "meyer lemon", "ruby grapefruit", "limequat"]),
        ("Berries", ["blueberry", "raspberry", "blackberry", "cranberry"]),
        ("Tropical Picks", ["pineapple", "mango", "papaya", "guava"]),
        ("Stone Fruits", ["nectarine", "apricot", "rainier cherry", "cling peach"]),
        ("Melon Varieties", ["cantaloupe", "honeydew", "watermelon", "galia melon"]),
        ("Apple Types", ["gala apple", "fuji apple", "honeycrisp apple", "braeburn apple"]),
        ("Pears", ["bartlett pear", "anjou pear", "comice pear", "seckel pear"]),
        ("Grapes", ["concord grape", "cotton candy grape", "thompson grape", "moon drop grape"]),
        ("Citrus Hybrids", ["tangelo", "ugli fruit", "kumquat", "yuzu"]),
        ("Banana Types", ["plantain", "cavendish banana", "red banana", "burro banana"]),
        ("Small Fruits", ["currant", "gooseberry", "huckleberry", "mulberry"]),
        ("Exotic Fruits", ["dragonfruit", "lychee", "longan", "rambutan"]),
        ("Tart Fruits", ["quince", "soursop", "tamarind", "persimmon"]),
        ("Tropical Citrus", ["calamansi", "finger lime", "bergamot", "pomelo"]),
        ("Fig & Date", ["mission fig", "kadota fig", "medjool date", "deglet date"]),
        ("Prickly Treats", ["prickly pear", "kiwano", "feijoa", "salak"]),
        ("Stone Berry Mix", ["boysenberry", "loganberry", "tayberry", "olallieberry"]),
        ("Summer Staples", ["pluot", "aprium", "white peach", "yellow plum"]),
        ("Farmstand Picks", ["sugar apple", "canistel", "cherimoya", "black sapote"]),
        ("Culinary Citrus", ["sudachi", "kabosu", "shonan gold", "mandarin"]),
    ],
    "Vegetables": [
        ("Leafy Greens", ["spinach", "kale", "romaine", "arugula"]),
        ("Root Vegetables", ["carrot", "beet", "parsnip", "turnip"]),
        ("Brassicas", ["broccoli", "cauliflower", "brussels sprout", "bok choy"]),
        ("Nightshades", ["eggplant", "bell pepper", "tomatillo", "jalapeno"]),
        ("Gourds", ["butternut squash", "acorn squash", "zucchini", "pumpkin"]),
        ("Alliums", ["yellow onion", "shallot", "leek", "garlic"]),
        ("Beans & Peas", ["green bean", "snow pea", "sugar snap", "lima bean"]),
        ("Stalk Veggies", ["celery", "fennel bulb", "kohlrabi", "asparagus"]),
        ("Tubers", ["russet potato", "red potato", "sweet potato", "yukon gold"]),
        ("Herbs", ["basil", "cilantro", "parsley", "dill"]),
        ("Mushrooms", ["shiitake", "portobello", "cremini", "enoki"]),
        ("Sprouts", ["alfalfa sprout", "bean sprout", "broccoli sprout", "radish sprout"]),
        ("Salad Mix", ["endive", "butter lettuce", "frisee", "watercress"]),
        ("Pickling Veg", ["kirby cucumber", "gherkin", "daikon", "pearl onion"]),
        ("Hot Peppers", ["serrano", "habanero", "poblano", "fresno pepper"]),
        ("Asian Greens", ["tatsoi", "choy sum", "mizuna", "mustard green"]),
        ("Sea Veggies", ["nori", "wakame", "kombu", "dulse"]),
        ("Flower Veg", ["artichoke", "broccolini", "romanesco", "caulilini"]),
        ("Microgreens", ["radish microgreen", "sunflower shoot", "pea tendril", "amaranth microgreen"]),
        ("Heirloom Picks", ["purple carrot", "rainbow chard", "striped beet", "candy cane pepper"]),
    ],
    "Food & Cooking": [
        ("Baking Essentials", ["all-purpose flour", "granulated sugar", "baking powder", "vanilla extract"]),
        ("Cooking Oils", ["olive oil", "canola oil", "sesame oil", "avocado oil"]),
        ("Spices", ["cumin", "paprika", "turmeric", "cinnamon"]),
        ("Kitchen Tools", ["chef knife", "cutting board", "mixing bowl", "whisk"]),
        ("Cookware", ["cast iron skillet", "saucepan", "stockpot", "roasting pan"]),
        ("Grains", ["white rice", "quinoa", "bulgur", "barley"]),
        ("Pasta Shapes", ["spaghetti", "penne", "fusilli", "farfalle"]),
        ("Cheeses", ["cheddar", "mozzarella", "gouda", "parmesan"]),
        ("Proteins", ["chicken breast", "pork chop", "salmon fillet", "tofu"]),
        ("Condiments", ["ketchup", "mayonnaise", "yellow mustard", "soy sauce"]),
        ("Breakfast Items", ["pancake", "waffle", "omelet", "granola"]),
        ("Desserts", ["brownie", "cheesecake", "cupcake", "tiramisu"]),
        ("Herbs & Aromatics", ["rosemary", "thyme", "sage", "lemongrass"]),
        ("Cured Meats", ["prosciutto", "salami", "bacon", "chorizo"]),
        ("Breads", ["baguette", "sourdough loaf", "pita", "brioche"]),
        ("Soups", ["chicken noodle soup", "tomato bisque", "clam chowder", "minestrone"]),
        ("Salads", ["caesar salad", "greek salad", "cobb salad", "waldorf salad"]),
        ("Dessert Toppings", ["whipped cream", "chocolate syrup", "sprinkles", "caramel sauce"]),
        ("Cooking Methods", ["grilling", "roasting", "steaming", "braising"]),
        ("Kitchen Appliances", ["blender", "toaster", "slow cooker", "air fryer"]),
    ],
    "Drinks & Beverages": [
        ("Morning Coffee", ["espresso", "americano", "latte", "cappuccino"]),
        ("Tea Varieties", ["green tea", "black tea", "oolong", "chamomile"]),
        ("Soft Drinks", ["cola", "ginger ale", "root beer", "lemon soda"]),
        ("Juices", ["orange juice", "apple juice", "grape juice", "cranberry juice"]),
        ("Smoothies", ["berry smoothie", "tropical smoothie", "green smoothie", "protein shake"]),
        ("Cocktails", ["mojito", "margarita", "old fashioned", "martini"]),
        ("Mocktails", ["virgin mary", "nojito", "sparkling lemonade", "cucumber cooler"]),
        ("Milk Drinks", ["milkshake", "chocolate milk", "bubble tea", "horchata"]),
        ("Energy Drinks", ["energy shot", "sports drink", "citrus booster", "berry blast"]),
        ("Craft Beer", ["pale ale", "ipa", "stout", "wheat beer"]),
        ("Wines", ["cabernet", "merlot", "chardonnay", "riesling"]),
        ("Winter Warmers", ["hot chocolate", "spiced cider", "mulled wine", "buttered rum"]),
        ("Summer Sips", ["iced tea", "lemonade", "agua fresca", "arnold palmer"]),
        ("Hydration", ["sparkling water", "mineral water", "coconut water", "aloe drink"]),
        ("Fermented Drinks", ["kombucha", "kvass", "kefir", "ginger beer"]),
        ("Brunch Drinks", ["bloody mary", "bellini", "mimosa", "irish coffee"]),
        ("Cafe Specials", ["flat white", "cortado", "affogato", "macchiato"]),
        ("Tea Lattes", ["chai latte", "matcha latte", "london fog", "royal milk tea"]),
        ("Protein Drinks", ["casein shake", "soy shake", "pea protein", "whey smoothie"]),
        ("Kid Favorites", ["fruit punch", "apple cider", "grape soda", "orange soda"]),
    ],
    "Animals": [
        ("Savannah Animals", ["lion", "cheetah", "gazelle", "wildebeest"]),
        ("Rainforest Life", ["jaguar", "tapir", "capybara", "macaw"]),
        ("Ocean Creatures", ["dolphin", "octopus", "stingray", "seahorse"]),
        ("Arctic Wildlife", ["polar bear", "walrus", "narwhal", "arctic fox"]),
        ("Birds of Prey", ["eagle", "falcon", "hawk", "osprey"]),
        ("Desert Animals", ["camel", "fennec fox", "meerkat", "jerboa"]),
        ("Farm Animals", ["cow", "sheep", "goat", "pig"]),
        ("Reptiles", ["komodo dragon", "iguana", "python", "crocodile"]),
        ("Amphibians", ["tree frog", "salamander", "axolotl", "newt"]),
        ("Primates", ["chimpanzee", "orangutan", "baboon", "lemur"]),
        ("Marsupials", ["kangaroo", "koala", "wallaby", "wombat"]),
        ("Coral Reef", ["clownfish", "parrotfish", "moray eel", "pufferfish"]),
        ("Mountain Fauna", ["ibex", "snow leopard", "yak", "marmot"]),
        ("Deep Sea", ["anglerfish", "vampire squid", "lanternfish", "gulper eel"]),
        ("Grassland Birds", ["ostrich", "emu", "cassowary", "rhea"]),
        ("Insects", ["stag beetle", "dragonfly", "mantis", "firefly"]),
        ("Pollinators", ["honeybee", "bumblebee", "hoverfly", "hummingbird"]),
        ("Aquatic Mammals", ["manatee", "beluga", "sea otter", "fur seal"]),
        ("Forest Dwellers", ["moose", "raccoon", "porcupine", "bobcat"]),
        ("Island Species", ["galapagos finch", "marine iguana", "albatross", "giant tortoise"]),
    ],
    "Pets": [
        ("Dog Breeds", ["labrador", "beagle", "poodle", "bulldog"]),
        ("Cat Breeds", ["siamese", "maine coon", "persian", "bengal cat"]),
        ("Small Mammals", ["hamster", "guinea pig", "ferret", "chinchilla"]),
        ("Aquarium Fish", ["goldfish", "betta", "angelfish", "molly"]),
        ("Bird Companions", ["parakeet", "cockatiel", "lovebird", "canary"]),
        ("Reptile Pets", ["leopard gecko", "corn snake", "bearded dragon", "red-eared slider"]),
        ("Working Dogs", ["german shepherd", "border collie", "rottweiler", "doberman"]),
        ("Toy Dogs", ["pomeranian", "shih tzu", "chihuahua", "yorkshire terrier"]),
        ("Herding Dogs", ["australian shepherd", "corgi", "sheltie", "old english sheepdog"]),
        ("Rare Cats", ["sphynx cat", "british shorthair", "scottish fold", "ragdoll"]),
        ("Rabbit Breeds", ["lop rabbit", "rex rabbit", "lionhead rabbit", "dutch rabbit"]),
        ("Pet Accessories", ["collar", "leash", "cat tree", "litter box"]),
        ("Pet Treats", ["dental chew", "jerky strip", "catnip toy", "seed stick"]),
        ("Pet Habitats", ["fish tank", "birdcage", "terrarium", "hutch"]),
        ("Training Gear", ["clicker", "treat pouch", "training pad", "agility tunnel"]),
        ("Pet Services", ["grooming", "boarding", "dog walking", "vet visit"]),
        ("Pet Health", ["flea collar", "heartworm pill", "scratching post", "water fountain"]),
        ("Pet Games", ["fetch ball", "laser pointer", "feather wand", "chew rope"]),
        ("Pet Beds", ["orthopedic bed", "heated pad", "window perch", "crate mat"]),
        ("Pet Nutrition", ["kibble", "wet food", "hay bale", "pellet mix"]),
    ],
    "Nature & Plants": [
        ("Forest Trees", ["oak", "maple", "pine", "birch"]),
        ("Wildflowers", ["daisy", "violet", "poppy", "bluebell"]),
        ("Desert Plants", ["saguaro", "yucca", "ocotillo", "prickly pear cactus"]),
        ("Wetland Plants", ["cattail", "lotus", "pickerelweed", "water lily"]),
        ("Mountain Flora", ["edelweiss", "larkspur", "alpine aster", "glacier lily"]),
        ("Grasses", ["fescue", "bermuda grass", "switchgrass", "ryegrass"]),
        ("Ferns", ["maidenhair fern", "bracken", "ostrich fern", "sword fern"]),
        ("Garden Shrubs", ["azalea", "hydrangea", "rhododendron", "boxwood"]),
        ("Climbing Plants", ["ivy", "wisteria", "clematis", "honeysuckle"]),
        ("Medicinal Herbs", ["echinacea", "lavender", "chamomile flower", "peppermint"]),
        ("Trees with Cones", ["spruce", "cedar", "fir", "cypress"]),
        ("Groundcovers", ["creeping thyme", "periwinkle", "ajuga", "sedum"]),
        ("Rainforest Plants", ["bromeliad", "monstera", "philodendron", "ginger lily"]),
        ("Wetland Trees", ["bald cypress", "willow", "mangrove", "cottonwood"]),
        ("Edible Plants", ["rhubarb", "watercress plant", "sorrel", "nasturtium"]),
        ("Pollinator Plants", ["coneflower", "bee balm", "milkweed", "black-eyed susan"]),
        ("Shade Plants", ["hosta", "astilbe", "heuchera", "lungwort"]),
        ("Succulents", ["aloe", "jade plant", "echeveria", "haworthia"]),
        ("Tropical Trees", ["banana tree", "breadfruit", "baobab", "mango tree"]),
        ("Prairie Plants", ["bluestem", "coneflower prairie", "indian grass", "goldenrod"]),
    ],
    "Weather & Climate": [
        ("Cloud Types", ["cumulus", "cirrus", "stratus", "nimbus"]),
        ("Storms", ["tornado", "hurricane", "blizzard", "thunderstorm"]),
        ("Precipitation", ["rain", "sleet", "hail", "drizzle"]),
        ("Wind Patterns", ["trade wind", "jet stream", "sea breeze", "mountain breeze"]),
        ("Severe Weather", ["derecho", "sandstorm", "ice storm", "dust devil"]),
        ("Climate Zones", ["tropical climate", "arid climate", "temperate climate", "polar climate"]),
        ("Seasonal Events", ["monsoon", "heatwave", "cold snap", "chinook"]),
        ("Sky Phenomena", ["rainbow", "aurora", "halo", "sun dog"]),
        ("Pressure Systems", ["high pressure", "low pressure", "cyclone", "anticyclone"]),
        ("Weather Instruments", ["barometer", "hygrometer", "anemometer", "rain gauge"]),
        ("Forecast Terms", ["front", "dew point", "visibility", "wind chill"]),
        ("Ocean Patterns", ["el nino", "la nina", "upwelling", "gulf stream"]),
        ("Drought Terms", ["water shortage", "dust bowl", "dry spell", "soil cracking"]),
        ("Winter Weather", ["snowflake", "frost", "black ice", "snowdrift"]),
        ("Summer Weather", ["heat index", "humidity", "sunshine", "thermal updraft"]),
        ("Storm Tracking", ["radar", "storm surge", "eye wall", "outer band"]),
        ("Cloudy Skies", ["overcast", "broken sky", "scattered cloud", "fog bank"]),
        ("Mountain Weather", ["avalanches", "whiteout", "cornice", "ridge wind"]),
        ("Calm Conditions", ["breeze", "lull", "still air", "light air"]),
        ("Coastal Weather", ["sea fog", "marine layer", "rip current", "coastal drizzle"]),
    ],
    "Space & Universe": [
        ("Planets", ["mercury", "venus", "earth", "mars"]),
        ("Gas Giants", ["jupiter", "saturn", "uranus", "neptune"]),
        ("Dwarf Planets", ["pluto", "ceres", "haumea", "eris"]),
        ("Moons", ["io", "europa", "ganymede", "callisto"]),
        ("Constellations", ["orion", "ursa major", "leo", "cassiopeia"]),
        ("Stars", ["red dwarf", "white dwarf", "supergiant", "neutron star"]),
        ("Galaxies", ["milky way", "andromeda", "triangulum", "whirlpool galaxy"]),
        ("Telescopes", ["hubble", "james webb", "keck", "arecibo"]),
        ("Spacecraft", ["voyager", "apollo", "soyuz", "dragon capsule"]),
        ("Astronaut Gear", ["space suit", "helmet", "oxygen tank", "glove"]),
        ("Rockets", ["falcon heavy", "atlas", "delta", "ariane"]),
        ("Satellites", ["gps satellite", "weather satellite", "spy satellite", "communication satellite"]),
        ("Space Phenomena", ["black hole", "quasar", "pulsar", "nebula"]),
        ("Meteors", ["meteor", "meteoroid", "meteorite", "bolide"]),
        ("Orbital Terms", ["orbit", "elliptical path", "escape velocity", "perigee"]),
        ("Space Stations", ["iss", "tiangong", "mir", "skylab"]),
        ("Launch Sites", ["cape canaveral", "baikonur", "vandenberg", "kourou"]),
        ("Robotic Landers", ["curiosity rover", "perseverance", "spirit rover", "insight lander"]),
        ("Space Agencies", ["nasa", "esa", "roscosmos", "jaxa"]),
        ("Asteroids", ["ceres belt", "vesta", "pallas", "hygiea"]),
    ],
    "Human Body & Health": [
        ("Major Organs", ["heart", "lungs", "liver", "kidneys"]),
        ("Bones", ["femur", "tibia", "humerus", "radius"]),
        ("Muscle Groups", ["biceps", "quadriceps", "hamstrings", "deltoid"]),
        ("Senses", ["sight", "hearing", "taste", "smell"]),
        ("Immune System", ["antibody", "white cell", "lymph node", "thymus"]),
        ("Digestive System", ["stomach", "intestine", "pancreas", "gallbladder"]),
        ("Respiratory", ["trachea", "bronchus", "diaphragm", "alveoli"]),
        ("Circulatory", ["aorta", "vein", "capillary", "artery"]),
        ("Brain Parts", ["cerebrum", "cerebellum", "hippocampus", "amygdala"]),
        ("Health Check", ["blood pressure", "pulse", "temperature", "respiration"]),
        ("First Aid", ["bandage", "splint", "antiseptic", "tourniquet"]),
        ("Medical Tests", ["x-ray", "mri", "blood panel", "ultrasound"]),
        ("Vaccines", ["tetanus shot", "flu shot", "measles vaccine", "polio vaccine"]),
        ("Therapies", ["physical therapy", "occupational therapy", "speech therapy", "respiratory therapy"]),
        ("Health Professions", ["nurse", "surgeon", "therapist", "paramedic"]),
        ("Dental Care", ["tooth", "molar", "gum", "enamel"]),
        ("Fitness Gear", ["dumbbell", "yoga mat", "resistance band", "kettlebell"]),
        ("Diet Items", ["multivitamin", "protein bar", "electrolyte drink", "meal replacement"]),
        ("Medical Devices", ["stethoscope", "thermometer", "blood cuff", "pulse oximeter"]),
        ("Wellness", ["meditation cushion", "foam roller", "sleep mask", "aroma diffuser"]),
    ],
    "Clothing & Fashion": [
        ("Casual Tops", ["t-shirt", "polo shirt", "henley", "tank top"]),
        ("Formal Wear", ["tuxedo", "evening gown", "dress shirt", "cocktail dress"]),
        ("Footwear", ["sneaker", "loafer", "ankle boot", "sandals"]),
        ("Outerwear", ["trench coat", "puffer jacket", "blazer", "raincoat"]),
        ("Accessories", ["scarf", "belt", "watch", "sunglasses"]),
        ("Hats", ["beanie", "fedora", "baseball cap", "sun hat"]),
        ("Denim", ["skinny jeans", "bootcut jeans", "denim jacket", "denim skirt"]),
        ("Athleisure", ["hoodie", "jogger", "sports bra", "track jacket"]),
        ("Formal Shoes", ["oxford shoe", "derby shoe", "monk strap", "patent pump"]),
        ("Bags", ["backpack", "tote bag", "clutch", "crossbody"]),
        ("Jewelry", ["necklace", "bracelet", "earring", "ring"]),
        ("Summer Wear", ["swimsuit", "cover-up", "flip-flop", "linen shirt"]),
        ("Winter Gear", ["wool coat", "mittens", "earmuffs", "thermal leggings"]),
        ("Workwear", ["work boots", "cargo pants", "utility vest", "hard hat"]),
        ("Sleepwear", ["pajamas", "robe", "nightgown", "sleep mask accessory"]),
        ("Underwear", ["boxers", "briefs", "undershirt", "bralette"]),
        ("Traditional Wear", ["kimono", "sari", "kilt", "dirndl"]),
        ("Sportswear", ["soccer jersey", "basketball short", "cleat", "compression shirt"]),
        ("Fabric Types", ["cotton", "linen", "wool", "silk"]),
        ("Closet Items", ["hanger", "garment bag", "shoe tree", "lint roller"]),
    ],
    "Home & Furniture": [
        ("Living Room", ["sofa", "coffee table", "armchair", "tv stand"]),
        ("Bedroom", ["bed frame", "nightstand", "dresser", "wardrobe"]),
        ("Kitchen", ["cabinet", "kitchen island", "barstool", "pantry shelf"]),
        ("Bathroom", ["vanity", "shower curtain", "bath mat", "towel rack"]),
        ("Lighting", ["floor lamp", "table lamp", "chandelier", "sconce"]),
        ("Decor", ["area rug", "wall art", "vase", "picture frame"]),
        ("Outdoor", ["patio chair", "picnic table", "hammock", "fire pit"]),
        ("Storage", ["bookshelf", "storage bin", "closet organizer", "shoe rack"]),
        ("Dining", ["dining table", "dining chair", "sideboard", "china cabinet"]),
        ("Entryway", ["console table", "coat rack", "umbrella stand", "welcome mat"]),
        ("Kids Room", ["bunk bed", "toy chest", "play table", "beanbag"]),
        ("Office", ["writing desk", "office chair", "filing cabinet", "bookcase"]),
        ("Laundry", ["washing machine", "dryer", "laundry basket", "ironing board"]),
        ("Garage", ["workbench", "storage pegboard", "utility shelf", "bike rack"]),
        ("Windows", ["curtains", "blinds", "roman shade", "valance"]),
        ("Flooring", ["hardwood", "tile", "carpet", "laminate"]),
        ("Bedding", ["comforter", "pillow", "sheet set", "duvet"]),
        ("Kitchenware", ["dinner plate", "cutlery set", "wine glass", "serving bowl"]),
        ("Plants Indoors", ["snake plant", "pothos", "succulent pot", "fiddle leaf fig"]),
        ("Home Safety", ["smoke alarm", "carbon monoxide detector", "fire extinguisher", "first aid kit"]),
    ],
    "Tools & Hardware": [
        ("Hand Tools", ["hammer", "screwdriver", "pliers", "wrench"]),
        ("Power Tools", ["drill", "circular saw", "jigsaw", "sander"]),
        ("Fasteners", ["nail", "wood screw", "bolt", "toggle anchor"]),
        ("Measuring", ["tape measure", "level", "caliper", "framing square"]),
        ("Cutting Tools", ["utility knife", "hacksaw", "chisel", "pruning shear"]),
        ("Safety Gear", ["goggles", "ear protection", "work glove", "hard hat tool"]),
        ("Painting Tools", ["paint roller", "paintbrush", "drop cloth", "paint tray"]),
        ("Adhesives", ["wood glue", "epoxy", "construction adhesive", "caulk"]),
        ("Plumbing", ["pipe wrench", "plunger", "pipe cutter", "thread tape"]),
        ("Electrical", ["wire stripper", "voltage tester", "outlet", "junction box"]),
        ("Yard Tools", ["shovel", "rake", "garden hoe", "wheelbarrow"]),
        ("Hardware Storage", ["toolbox", "pegboard hook", "screw bin", "parts organizer"]),
        ("Sanding", ["sandpaper", "sanding block", "orbital sander", "belt sander"]),
        ("Concrete Tools", ["trowel", "bull float", "concrete mixer", "edger"]),
        ("Ladders", ["step ladder", "extension ladder", "platform ladder", "folding ladder"]),
        ("Clamp Types", ["c-clamp", "bar clamp", "spring clamp", "pipe clamp"]),
        ("Saw Blades", ["rip blade", "crosscut blade", "diamond blade", "reciprocating blade"]),
        ("Welding", ["welding mask", "welding rod", "welding torch", "slag hammer"]),
        ("Automotive Tools", ["socket wrench", "torque wrench", "impact driver", "creeper"]),
        ("Shop Supplies", ["shop vacuum", "drop cord", "work light", "bench vise"]),
    ],
    "Technology & Gadgets": [
        ("Smartphones", ["touchscreen phone", "android phone", "iphone", "foldable phone"]),
        ("Computers", ["laptop", "desktop", "gaming rig", "ultrabook"]),
        ("Tablets", ["android tablet", "ipad", "e-reader", "drawing tablet"]),
        ("Wearables", ["smartwatch", "fitness tracker", "vr headset", "smart glasses"]),
        ("Audio Gear", ["wireless earbuds", "over-ear headphone", "soundbar", "bluetooth speaker"]),
        ("Cameras", ["dslr", "mirrorless camera", "action camera", "camcorder"]),
        ("Home Tech", ["smart thermostat", "smart bulb", "smart plug", "home hub"]),
        ("Gaming", ["game console", "gaming controller", "vr controller", "gaming mouse"]),
        ("Networking", ["wifi router", "mesh system", "ethernet switch", "modem"]),
        ("Storage", ["ssd drive", "external hard drive", "usb flash", "network nas"]),
        ("Peripherals", ["mechanical keyboard", "wireless mouse", "webcam", "monitor"]),
        ("PC Components", ["graphics card", "motherboard", "cpu", "power supply"]),
        ("Printers", ["inkjet printer", "laser printer", "3d printer", "photo printer"]),
        ("Mobile Accessories", ["phone case", "screen protector", "portable charger", "car mount"]),
        ("Smart Home Security", ["video doorbell", "security camera", "smart lock", "motion sensor"]),
        ("Cloud Services", ["cloud backup", "file sync", "streaming service", "online storage"]),
        ("Software", ["operating system", "office suite", "photo editor", "video editor"]),
        ("Kitchen Gadgets", ["smart kettle", "precision cooker", "kitchen scale", "coffee grinder"]),
        ("Emerging Tech", ["drone", "robot vacuum", "smart tag", "augmented reality kit"]),
        ("Charging", ["usb-c cable", "wireless charger", "power bank", "charging dock"]),
    ],
    "Transportation": [
        ("Cars", ["sedan", "coupe", "convertible", "hatchback"]),
        ("Public Transit", ["city bus", "subway", "tram", "ferry"]),
        ("Bikes", ["mountain bike", "road bike", "bmx", "cruiser"]),
        ("Air Travel", ["airplane", "jet", "glider", "seaplane"]),
        ("Rail", ["freight train", "bullet train", "commuter train", "monorail"]),
        ("Watercraft", ["sailboat", "yacht", "canoe", "kayak"]),
        ("Trucks", ["pickup truck", "semi truck", "box truck", "dump truck"]),
        ("Motorcycles", ["sport bike", "cruiser motorcycle", "scooter", "moped"]),
        ("Construction Vehicles", ["bulldozer", "excavator", "backhoe", "grader"]),
        ("Emergency Vehicles", ["ambulance", "fire engine", "police cruiser", "rescue helicopter"]),
        ("Space Travel", ["shuttle", "rocket", "lander", "space plane"]),
        ("Electric Vehicles", ["electric car", "electric scooter", "electric bike", "electric bus"]),
        ("Recreational Vehicles", ["camper van", "motorhome", "travel trailer", "fifth wheel"]),
        ("Agricultural Vehicles", ["tractor", "combine", "baler", "planter"]),
        ("Cargo Transport", ["cargo ship", "freighter", "barge", "container ship"]),
        ("Airport Vehicles", ["luggage cart", "pushback tug", "fuel truck", "catering truck"]),
        ("Snow Transport", ["snowmobile", "snowcat", "snowplow", "sled"]),
        ("Personal Mobility", ["skateboard", "rollerblade", "hoverboard", "kick scooter"]),
        ("Ride Services", ["taxi", "rideshare", "shuttle van", "charter bus"]),
        ("Navigation", ["compass", "map", "gps unit", "sextant"]),
    ],
    "Sports & Activities": [
        ("Team Sports", ["basketball", "soccer", "baseball", "hockey"]),
        ("Racquet Sports", ["tennis", "badminton", "squash", "pickleball"]),
        ("Water Sports", ["swimming", "water polo", "surfing", "rowing"]),
        ("Winter Sports", ["ski", "snowboard", "ice skate", "luge"]),
        ("Track & Field", ["sprint", "long jump", "shot put", "pole vault"]),
        ("Combat Sports", ["boxing", "karate", "judo", "taekwondo"]),
        ("Fitness Activities", ["crossfit", "spinning", "pilates", "aerobics"]),
        ("Outdoor Adventures", ["hiking", "camping", "rock climbing", "orienteering"]),
        ("Cycling Events", ["time trial", "road race", "bmx park", "cyclocross"]),
        ("Court Games", ["volleyball", "handball", "futsal", "netball"]),
        ("Recreational Games", ["bowling", "darts", "billiards", "shuffleboard"]),
        ("Gymnastics", ["balance beam", "vault", "uneven bars", "pommel horse"]),
        ("Athletic Gear", ["dumbbell rack", "kettlebell set", "medicine ball", "jump rope"]),
        ("Yoga Styles", ["hatha yoga", "vinyasa", "hot yoga", "yin yoga"]),
        ("Dance Styles", ["ballet", "salsa", "hip hop", "tango"]),
        ("Running Events", ["marathon", "half marathon", "10k", "5k"]),
        ("Field Sports", ["lacrosse", "rugby", "cricket", "ultimate frisbee"]),
        ("Target Sports", ["archery", "skeet", "air rifle", "crossbow"]),
        ("Beach Activities", ["beach volleyball", "sandcastle", "snorkeling", "paddleboard"]),
        ("Mind Games", ["chess", "checkers", "sudoku", "crossword"]),
    ],
    "Hobbies & Leisure": [
        ("Crafts", ["knitting", "crochet", "quilting", "scrapbook"]),
        ("Collecting", ["coin collection", "stamp album", "comic book", "trading card"]),
        ("Gardening", ["vegetable patch", "flower bed", "bonsai", "herb garden"]),
        ("Board Games", ["settlers", "ticket to ride", "monopoly", "catan expansion"]),
        ("Reading", ["novel", "mystery book", "graphic novel", "biography"]),
        ("Writing", ["journal", "short story", "poetry", "memoir"]),
        ("Photography", ["portrait shot", "landscape photo", "macro image", "street photo"]),
        ("Cooking Hobby", ["bread baking", "sourdough starter", "home canning", "meal prep"]),
        ("DIY Projects", ["woodworking", "home repair", "craft painting", "upcycling"]),
        ("Gaming", ["console game", "pc game", "tabletop rpg", "mobile game"]),
        ("Outdoors", ["birdwatching", "geocaching", "stargazing", "kayak trip"]),
        ("Music Enjoyment", ["vinyl record", "concert ticket", "playlist", "open mic"]),
        ("Fitness Hobby", ["trail run", "spin class", "yoga session", "gym visit"]),
        ("Art", ["watercolor", "oil painting", "charcoal sketch", "clay sculpting"]),
        ("Languages", ["spanish study", "french lesson", "japanese practice", "german vocab"]),
        ("Volunteering", ["food pantry", "animal shelter", "park cleanup", "tutoring"],),
        ("Travel Planning", ["itinerary", "guidebook", "packing list", "travel journal"]),
        ("Fishing", ["tackle box", "fishing rod", "bait bucket", "bobber"]),
        ("Model Making", ["model train", "plastic kit", "diorama", "miniature figure"]),
        ("Card Games", ["poker", "contract bridge", "blackjack", "hearts"]),
    ],
    "Music & Instruments": [
        ("String Instruments", ["violin", "viola", "cello", "double bass"]),
        ("Guitars", ["acoustic guitar", "electric guitar", "bass guitar", "ukulele"]),
        ("Keyboards", ["piano", "organ", "synthesizer", "harpsichord"]),
        ("Brass", ["trumpet", "trombone", "french horn", "tuba"]),
        ("Woodwinds", ["flute", "clarinet", "oboe", "bassoon"]),
        ("Percussion", ["snare drum", "bass drum", "xylophone", "timpani"]),
        ("World Instruments", ["sitar", "tabla", "pan flute", "didgeridoo"]),
        ("Electronic Gear", ["drum machine", "sampler", "midi controller", "audio interface"]),
        ("Band Roles", ["vocalist", "guitarist", "drummer", "bassist"]),
        ("Music Genres", ["rock", "jazz", "classical", "hip-hop"]),
        ("Orchestra Sections", ["strings", "brass section", "woodwind section", "percussion section"]),
        ("Recording", ["microphone", "studio monitor", "mixing console", "pop filter"]),
        ("Live Sound", ["stage monitor", "line array", "lighting rig", "stage riser"]),
        ("Choir", ["soprano", "alto", "tenor", "bass voice"]),
        ("Music Theory", ["scale", "chord", "interval", "rhythm"]),
        ("Songwriting", ["verse", "chorus", "bridge", "hook"]),
        ("Practice Tools", ["metronome", "tuner", "sheet music", "music stand"]),
        ("DJ Gear", ["turntable", "mixer", "dj controller", "headphones dj"]),
        ("Marching Band", ["snareline", "color guard", "brass line", "drum major"]),
        ("Opera", ["aria", "libretto", "overture", "recitative"]),
    ],
    "Movies & TV": [
        ("Genres", ["comedy", "drama", "thriller", "fantasy"]),
        ("Streaming Services", ["netflix", "hulu", "disney plus", "prime video"]),
        ("Film Roles", ["director", "producer", "screenwriter", "cinematographer"]),
        ("TV Roles", ["anchor", "showrunner", "newscaster", "talk host"]),
        ("Award Shows", ["oscars", "emmys", "golden globes", "baftas"]),
        ("Animated Films", ["pixar film", "anime movie", "claymation", "stop motion"]),
        ("Movie Snacks", ["popcorn", "nachos", "candy bar", "soft pretzel"]),
        ("Cinema Rooms", ["theater screen", "concession stand", "projection booth", "stadium seat"]),
        ("TV Equipment", ["remote control", "set-top box", "sound system", "streaming stick"]),
        ("Film Techniques", ["montage", "close-up", "dolly shot", "wide shot"]),
        ("Reality TV", ["talent show", "cooking contest", "home makeover", "dating show"]),
        ("Sci-Fi Tropes", ["time travel", "alien invasion", "cyberpunk city", "space opera"]),
        ("Classic Films", ["silent film", "noir", "western", "musical"]),
        ("TV Formats", ["sitcom", "miniseries", "soap opera", "news magazine"]),
        ("Production Gear", ["boom mic", "lighting kit", "clapboard", "camera dolly"]),
        ("Fan Culture", ["cosplay", "fan club", "convention badge", "fan theory"]),
        ("Home Theater", ["soundbar tv", "subwoofer", "projector", "screen curtain"]),
        ("Film Music", ["soundtrack", "score", "theme song", "leitmotif"]),
        ("Binge Night", ["pilot episode", "cliffhanger", "series finale", "rewatch"]),
        ("Cinema Jobs", ["usher", "projectionist", "ticket taker", "concession worker"]),
    ],
    "Jobs & Professions": [
        ("Medical Careers", ["doctor", "nurse practitioner", "pharmacist", "radiologist"]),
        ("Technology Careers", ["software engineer", "data analyst", "system admin", "ux designer"]),
        ("Education Careers", ["teacher", "professor", "school counselor", "librarian"]),
        ("Construction Jobs", ["carpenter", "electrician", "plumber", "mason"]),
        ("Legal Field", ["lawyer", "paralegal", "judge", "court clerk"]),
        ("Creative Jobs", ["graphic designer", "illustrator", "copywriter", "photographer pro"]),
        ("Business Roles", ["accountant", "project manager", "consultant", "hr specialist"]),
        ("Hospitality", ["chef", "hotel manager", "bartender", "server"]),
        ("Public Service", ["firefighter", "police officer", "paramedic responder", "postal worker"]),
        ("Transportation Jobs", ["pilot", "bus driver", "train conductor", "truck driver"]),
        ("Manufacturing", ["machinist", "assembler", "quality inspector", "plant manager"]),
        ("Agriculture", ["farmer", "rancher", "agronomist", "beekeeper"]),
        ("Science Roles", ["biologist", "chemist", "physicist", "geologist"]),
        ("Finance", ["banker", "financial advisor", "loan officer", "auditor"]),
        ("Sports Jobs", ["coach", "referee", "scout", "athletic trainer"]),
        ("Media Jobs", ["journalist", "editor", "radio host", "camera operator"]),
        ("Retail", ["cashier", "store manager", "sales associate", "stock clerk"]),
        ("Skilled Trades", ["welder", "hvac technician", "roofer", "glazier"]),
        ("Maritime", ["sailor", "harbor pilot", "ship captain", "dock worker"]),
        ("Animal Care", ["veterinarian", "zookeeper", "animal trainer", "pet groomer"]),
    ],
    "School & Education": [
        ("Classroom Items", ["chalkboard", "desk", "chair", "textbook"]),
        ("Subjects", ["mathematics", "history", "science", "literature"]),
        ("School Staff", ["principal", "counselor", "coach teacher", "janitor"]),
        ("Student Life", ["school backpack", "locker", "field trip", "report card"]),
        ("School Supplies", ["notebook", "pencil", "calculator", "binder"]),
        ("Assessments", ["quiz", "exam", "essay", "presentation"]),
        ("Extracurriculars", ["band", "debate club", "art club", "robotics team"]),
        ("Higher Education", ["lecture hall", "lab", "dormitory", "campus library"]),
        ("Graduation", ["cap", "gown", "diploma", "honor cord"]),
        ("Sports at School", ["school gym", "track", "bleachers", "scoreboard"]),
        ("Class Formats", ["lecture", "seminar", "workshop", "lab session"]),
        ("Early Learning", ["alphabet chart", "crayon", "building blocks", "story time"]),
        ("Online Learning", ["learning portal", "video lesson", "discussion board", "quiz module"]),
        ("Testing Prep", ["flashcard", "study guide", "practice test", "timer"]),
        ("Library Items", ["library card", "catalog", "reading nook", "check-out desk"]),
        ("Administrative", ["attendance sheet", "syllabus", "progress report", "parent letter"]),
        ("Scholarships", ["grant", "fellowship", "scholarship", "tuition waiver"]),
        ("Science Lab", ["microscope", "beaker", "bunsen burner", "petri dish"]),
        ("Art Class", ["easel", "paint palette", "clay wheel", "sketchbook"]),
        ("Language Class", ["dictionary", "flashcard set", "grammar book", "language tape"]),
    ],
    "Places & Travel": [
        ("Major Cities", ["new york", "los angeles", "chicago", "houston"]),
        ("Famous Landmarks", ["statue of liberty", "eiffel tower", "great wall", "big ben"]),
        ("Natural Wonders", ["grand canyon", "niagara falls", "mount everest", "aurora borealis"]),
        ("Beaches", ["bondi beach", "waikiki", "cancun beach", "malibu"]),
        ("Mountains", ["rockies", "andes", "alps", "himalayas"]),
        ("Parks", ["yellowstone", "yosemite", "banff", "kruger park"]),
        ("Islands", ["bali", "iceland", "bahamas", "madagascar"]),
        ("Transportation Hubs", ["airport", "train station", "bus terminal", "seaport"]),
        ("Hotels", ["resort", "boutique hotel", "hostel", "bed and breakfast"]),
        ("Cultural Sites", ["museum", "art gallery", "historic fort", "temple"]),
        ("Adventure Travel", ["safari", "trek", "rafting trip", "zipline park"]),
        ("Desert Destinations", ["sahara", "gobi", "mojave", "atacama"]),
        ("Coastal Towns", ["monterey", "charleston", "savannah", "bar harbor"]),
        ("Countryside", ["vineyard", "orchard", "farm stay", "country lane"]),
        ("Theme Parks", ["disneyland", "universal studios", "six flags", "dollywood"]),
        ("Archaeology", ["pyramid", "ruins", "ancient temple", "dig site"]),
        ("Urban Attractions", ["skyscraper", "city plaza", "market street", "harborfront"]),
        ("Winter Escapes", ["ski resort", "mountain lodge", "hot spring", "igloo hotel"]),
        ("Tropical Getaways", ["lagoon", "reef", "jungle lodge", "palm cove"]),
        ("Travel Documents", ["passport", "boarding pass", "visa", "travel insurance"]),
    ],
    "Holidays & Traditions": [
        ("Winter Holidays", ["christmas", "hanukkah", "kwanzaa", "new year"]),
        ("Spring Holidays", ["easter", "passover", "ramadan", "holi"]),
        ("Summer Holidays", ["independence day", "bastille day", "canada day", "midsummer"]),
        ("Fall Holidays", ["thanksgiving", "diwali", "harvest festival", "rosh hashanah"]),
        ("Decorations", ["ornament", "garland", "wreath", "lantern"]),
        ("Parades", ["float", "marching band parade", "balloon", "street performer"]),
        ("Traditional Foods", ["roast turkey", "latke", "matzah", "moon cake"]),
        ("Festive Drinks", ["eggnog", "mulled cider", "sparkling wine", "holiday punch"]),
        ("Gift Giving", ["gift wrap", "stocking", "gift card", "ribbon"]),
        ("Winter Traditions", ["snowman", "ice rink", "caroling", "holiday market"]),
        ("Cultural Customs", ["tea ceremony", "lion dance", "bonfire night", "lantern release"]),
        ("Family Gatherings", ["dinner table", "family reunion", "potluck", "game night"]),
        ("New Year Traditions", ["countdown", "fireworks", "midnight toast", "confetti"],),
        ("Religious Events", ["mass", "temple visit", "pilgrimage", "baptism"]),
        ("Festive Music", ["carol", "holiday playlist", "choir performance", "street musician"]),
        ("Holiday Crafts", ["gingerbread house", "paper snowflake", "ornament making", "wreath craft"]),
        ("Community Events", ["tree lighting", "street fair", "farmers market", "block party"]),
        ("Autumn Traditions", ["pumpkin patch", "corn maze", "hayride", "apple picking"]),
        ("Valentine Traditions", ["valentine card", "chocolate box", "flower bouquet", "romantic dinner"]),
        ("Patriotic Traditions", ["flag raising", "national anthem", "firework display", "parade route"]),
    ],
    "Colors & Shapes": [
        ("Primary Colors", ["red", "blue", "yellow", "green"]),
        ("Secondary Colors", ["orange", "purple", "teal", "magenta"]),
        ("Neutral Tones", ["beige", "gray", "ivory", "taupe"]),
        ("Earthy Shades", ["olive", "rust", "terracotta", "mustard"]),
        ("Pastel Shades", ["lilac", "mint", "peach", "baby blue"]),
        ("Bright Shades", ["neon pink", "lime", "electric blue", "chartreuse"]),
        ("Metallics", ["gold", "silver", "bronze", "copper"]),
        ("Patterns", ["striped", "polka dot", "plaid", "chevron"]),
        ("Basic Shapes", ["circle", "square", "triangle", "rectangle"]),
        ("3D Shapes", ["cube", "sphere", "cylinder", "cone"]),
        ("Math Shapes", ["rhombus", "trapezoid", "parallelogram", "octagon"]),
        ("Star Shapes", ["five-point star", "six-point star", "eight-point star", "shooting star"]),
        ("Curves", ["arc", "spiral", "oval", "ellipse"]),
        ("Lines", ["straight line", "dashed line", "zigzag", "wavy line"]),
        ("Textures", ["matte", "glossy", "satin", "metallic finish"]),
        ("Warm Tones", ["crimson", "scarlet", "amber", "marigold"]),
        ("Cool Tones", ["navy", "turquoise", "indigo", "slate"]),
        ("Natural Colors", ["forest green", "sky blue", "sand", "clay"]),
        ("Monochrome", ["charcoal", "graphite", "pearl", "snow"]),
        ("Gem Tones", ["emerald", "ruby", "sapphire", "amethyst"]),
    ],
    "Emotions & Personality": [
        ("Happy Feelings", ["joy", "delight", "cheer", "bliss"]),
        ("Sad Feelings", ["sorrow", "melancholy", "gloom", "despair"]),
        ("Calm States", ["serenity", "peace", "tranquility", "relaxation"]),
        ("Anger States", ["rage", "fury", "irritation", "wrath"]),
        ("Confidence", ["courage", "boldness", "assurance", "bravery"]),
        ("Curiosity", ["wonder", "inquisitiveness", "interest", "fascination"]),
        ("Trust Traits", ["honesty", "integrity", "reliability", "loyalty"]),
        ("Energy Levels", ["enthusiasm", "vigor", "drive", "zest"]),
        ("Social Traits", ["friendliness", "kindness", "empathy", "patience"]),
        ("Leadership", ["initiative", "vision", "charisma", "resolve"]),
        ("Creativity", ["imagination", "ingenuity", "originality", "resourcefulness"]),
        ("Anxiety", ["nervousness", "worry", "unease", "apprehension"]),
        ("Motivation", ["ambition", "determination", "persistence", "grit"]),
        ("Playfulness", ["humor", "mischief", "whimsy", "lightheartedness"]),
        ("Caring", ["compassion", "nurturing", "generosity", "support"]),
        ("Respect", ["courtesy", "humility", "tact", "politeness"]),
        ("Resilience", ["patience trait", "endurance", "fortitude", "tenacity"]),
        ("Alertness", ["awareness", "attentiveness", "vigilance", "focus"]),
        ("Honorable", ["fairness", "responsibility", "ethics", "credibility"]),
        ("Curated Quiet", ["silence", "stillness", "composure", "poise"]),
    ],
}

# Validate counts and uniqueness
all_words = set()
for cat, topics in categories.items():
    if len(topics) != 20:
        raise ValueError(f"Category {cat} does not have 20 topics")
    for topic_name, words in topics:
        if len(words) != 4:
            raise ValueError(f"Topic {topic_name} in {cat} does not have 4 words")
        for w in words:
            if w in all_words:
                raise ValueError(f"Duplicate word detected: {w}")
            all_words.add(w)

if len(all_words) != 2000:
    raise ValueError(f"Expected 2000 unique words, got {len(all_words)}")

# Write CSV
with open("Row Sort - Data Temp - ListTopicData-Word.csv", "w", encoding="utf-8") as f:
    f.write("CategoryID,CategoryName,TopicID,TopicName,TopicDifficult,TileID,TileName,TileImg\n")
    for cat_id, (cat_name, topics) in enumerate(categories.items(), start=1):
        for topic_id, (topic_name, words) in enumerate(topics, start=1):
            f.write(f"{cat_id},{cat_name},{topic_id},{topic_name},Normal,1,{words[0]},\n")
            for tile_id, word in enumerate(words[1:], start=2):
                f.write(f",,,,,{tile_id},{word},\n")
print("CSV generated with", len(all_words), "unique words")
